apiVersion: v1
kind: Secret
metadata:
  name: identity-secret-for-components
  #name: camunda-keycloak
type: Opaque
data:
  identity-secret: b0hDZk1yYzFCRkE1Y0RycWRoNEtyamVHSzg2OUxGNmMK
  operate-secret: c2VjcmV0LXZhbHVlLWZvci1vcGVyYXRl # Base64-encoded value for operate-secret
  tasklist-secret: c2VjcmV0LXZhbHVlLWZvci10YXNrbGlzdA== # Base64-encoded value for tasklist-secret
  optimize-secret: c2VjcmV0LXZhbHVlLWZvci1vcHRpbWl6ZQ== # Base64-encoded value for optimize-secret
  connectors-secret: c2VjcmV0LXZhbHVlLWZvci1jb25uZWN0b3Jz # Base64-encoded value for connectors-secret
  console-secret: c2VjcmV0LXZhbHVlLWZvci1jb25zb2xl # Base64-encoded value for console-secret
  keycloak-secret: c2VjcmV0LXZhbHVlLWZvci1rZXljbG9hay1zZWNyZXQ= # Base64-encoded value for keycloak-secret
  zeebe-secret: c2VjcmV0LXZhbHVlLWZvci16ZWViZS1zZWNyZXQ= # Base64-encoded value for zeebe-secret
  postgres-password: cGFzc3dvcmQxMjM= # Base64-encoded PostgreSQL password (e.g. 'password123')
  postgres-user: cG9zdGdyZXM=  # Base64-encoded PostgreSQL user (e.g. 'postgres')
  postgres-database: Y2FtdW5kYQ== # Base64-encoded PostgreSQL database name (e.g. 'camunda')
  password: cG9zdGdyZXM=
  admin-password: YWRtaW4=
  management-password: YWRtaW4=

#echo -n 'password123' | base64